name: test
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.36",
            "5.28",
            "5.18",
            "5.14",
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends .
      - name: Run test
        run: prove -lr t

